export const categories = [
  {
    id: 1,
    name: "Men's Clothing",
    slug: "men",
    image: "/images/category-men.jpg",
  },
  {
    id: 2,
    name: "Women's Clothing",
    slug: "women",
    image: "/images/category-women.jpg",
  },
  {
    id: 3,
    name: "Accessories",
    slug: "accessories",
    image: "/images/category-accessories.jpg",
  },
  {
    id: 4,
    name: "Footwear",
    slug: "footwear",
    image: "/images/category-footwear.jpg",
  },
]

export const featuredProducts = [
  {
    id: 1,
    name: "Classic White T-Shirt",
    description: "Essential cotton t-shirt for everyday wear",
    price: 29.99,
    discount: 0,
    image: "/images/product-1.jpg",
    category: "Men's Clothing",
    isNew: true,
    colors: ["white", "black", "gray"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    description: "Comfortable stretch denim for a modern look",
    price: 59.99,
    discount: 15,
    image: "/images/product-2.jpg",
    category: "Men's Clothing",
    isNew: false,
    colors: ["blue", "black"],
    sizes: ["30", "32", "34", "36"],
  },
  {
    id: 3,
    name: "Summer Floral Dress",
    description: "Light and breezy dress perfect for summer days",
    price: 49.99,
    discount: 0,
    image: "/images/product-3.jpg",
    category: "Women's Clothing",
    isNew: true,
    colors: ["floral", "blue", "pink"],
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 4,
    name: "Leather Crossbody Bag",
    description: "Stylish and practical bag for everyday essentials",
    price: 79.99,
    discount: 10,
    image: "/images/product-4.jpg",
    category: "Accessories",
    isNew: false,
    colors: ["brown", "black", "tan"],
    sizes: [],
  },
  {
    id: 5,
    name: "Canvas Sneakers",
    description: "Casual and comfortable footwear for any occasion",
    price: 39.99,
    discount: 0,
    image: "/images/product-5.jpg",
    category: "Footwear",
    isNew: false,
    colors: ["white", "black", "navy"],
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    id: 6,
    name: "Oversized Hoodie",
    description: "Cozy and stylish hoodie for cooler days",
    price: 54.99,
    discount: 0,
    image: "/images/product-6.jpg",
    category: "Women's Clothing",
    isNew: true,
    colors: ["gray", "black", "pink"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 7,
    name: "Aviator Sunglasses",
    description: "Classic style with UV protection",
    price: 24.99,
    discount: 0,
    image: "/images/product-7.jpg",
    category: "Accessories",
    isNew: false,
    colors: ["gold", "silver", "black"],
    sizes: [],
  },
  {
    id: 8,
    name: "Leather Wallet",
    description: "Slim design with multiple card slots",
    price: 34.99,
    discount: 0,
    image: "/images/product-8.jpg",
    category: "Accessories",
    isNew: false,
    colors: ["brown", "black"],
    sizes: [],
  },
]

export const allProducts = [
  ...featuredProducts,
  {
    id: 9,
    name: "Denim Jacket",
    description: "Classic denim jacket for layering",
    price: 69.99,
    discount: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "Men's Clothing",
    isNew: false,
    colors: ["blue", "black", "light-wash"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 10,
    name: "Pleated Midi Skirt",
    description: "Elegant skirt for office or casual wear",
    price: 44.99,
    discount: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "Women's Clothing",
    isNew: false,
    colors: ["black", "navy", "beige"],
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 11,
    name: "Leather Belt",
    description: "Quality leather belt with classic buckle",
    price: 29.99,
    discount: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "Accessories",
    isNew: false,
    colors: ["brown", "black"],
    sizes: ["S", "M", "L"],
  },
  {
    id: 12,
    name: "Running Shoes",
    description: "Lightweight and supportive for active lifestyles",
    price: 89.99,
    discount: 20,
    image: "/placeholder.svg?height=500&width=500",
    category: "Footwear",
    isNew: false,
    colors: ["black", "gray", "blue"],
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    id: 13,
    name: "Cashmere Sweater",
    description: "Luxuriously soft and warm sweater",
    price: 129.99,
    discount: 15,
    image: "/placeholder.svg?height=500&width=500",
    category: "Women's Clothing",
    isNew: false,
    colors: ["cream", "gray", "black"],
    sizes: ["S", "M", "L"],
  },
  {
    id: 14,
    name: "Chino Pants",
    description: "Versatile pants for work or weekend",
    price: 49.99,
    discount: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "Men's Clothing",
    isNew: false,
    colors: ["khaki", "navy", "olive"],
    sizes: ["30", "32", "34", "36"],
  },
  {
    id: 15,
    name: "Beanie Hat",
    description: "Warm knit hat for cold weather",
    price: 19.99,
    discount: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "Accessories",
    isNew: true,
    colors: ["black", "gray", "red"],
    sizes: [],
  },
  {
    id: 16,
    name: "Ankle Boots",
    description: "Stylish boots for fall and winter",
    price: 79.99,
    discount: 0,
    image: "/placeholder.svg?height=500&width=500",
    category: "Footwear",
    isNew: true,
    colors: ["black", "brown"],
    sizes: ["6", "7", "8", "9"],
  },
]
